<?php

use Illuminate\Database\Seeder;

class ActionTransactionsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::connection('pgsql')->table('action_transactions')->delete();
        
        \DB::connection('pgsql')->table('action_transactions')->insert(array (
            0 => 
            array (
                'id' => 281,
                'user_id' => 17,
                'action_id' => 13,
                'mail_template_id' => 4,
                'message' => NULL,
                'created_at' => '2016-11-02 04:35:01',
                'updated_at' => '2016-11-02 04:35:01',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            1 => 
            array (
                'id' => 280,
                'user_id' => 60,
                'action_id' => 13,
                'mail_template_id' => 6,
                'message' => NULL,
                'created_at' => '2016-10-26 01:57:21',
                'updated_at' => '2016-10-26 01:57:21',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            2 => 
            array (
                'id' => 279,
                'user_id' => 97,
                'action_id' => 12,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-10-21 07:58:02',
                'updated_at' => '2016-10-21 07:58:02',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            3 => 
            array (
                'id' => 278,
                'user_id' => 96,
                'action_id' => 12,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-10-18 23:10:01',
                'updated_at' => '2016-10-18 23:10:01',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            4 => 
            array (
                'id' => 277,
                'user_id' => 95,
                'action_id' => 13,
                'mail_template_id' => 6,
                'message' => NULL,
                'created_at' => '2016-10-14 14:11:35',
                'updated_at' => '2016-10-14 14:11:35',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            5 => 
            array (
                'id' => 276,
                'user_id' => 90,
                'action_id' => 24,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-10-14 08:56:42',
                'updated_at' => '2016-10-14 08:56:42',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            6 => 
            array (
                'id' => 275,
                'user_id' => 90,
                'action_id' => 26,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-10-14 08:56:39',
                'updated_at' => '2016-10-14 08:56:39',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            7 => 
            array (
                'id' => 274,
                'user_id' => 90,
                'action_id' => 34,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-10-14 08:56:38',
                'updated_at' => '2016-10-14 08:56:38',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            8 => 
            array (
                'id' => 273,
                'user_id' => 90,
                'action_id' => 32,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-10-14 08:56:36',
                'updated_at' => '2016-10-14 08:56:36',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            9 => 
            array (
                'id' => 272,
                'user_id' => 90,
                'action_id' => 29,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-10-14 08:56:34',
                'updated_at' => '2016-10-14 08:56:34',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            10 => 
            array (
                'id' => 271,
                'user_id' => 90,
                'action_id' => 31,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-10-14 08:56:31',
                'updated_at' => '2016-10-14 08:56:31',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            11 => 
            array (
                'id' => 270,
                'user_id' => 90,
                'action_id' => 19,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-10-14 08:56:15',
                'updated_at' => '2016-10-14 08:56:15',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            12 => 
            array (
                'id' => 269,
                'user_id' => 90,
                'action_id' => 13,
                'mail_template_id' => 4,
                'message' => NULL,
                'created_at' => '2016-10-14 08:52:14',
                'updated_at' => '2016-10-14 08:52:14',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            13 => 
            array (
                'id' => 268,
                'user_id' => 80,
                'action_id' => 13,
                'mail_template_id' => 7,
                'message' => NULL,
                'created_at' => '2016-10-13 05:13:34',
                'updated_at' => '2016-10-13 05:13:34',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            14 => 
            array (
                'id' => 267,
                'user_id' => 95,
                'action_id' => 12,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-10-12 14:26:35',
                'updated_at' => '2016-10-12 14:26:35',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            15 => 
            array (
                'id' => 266,
                'user_id' => 94,
                'action_id' => 12,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-10-11 06:51:42',
                'updated_at' => '2016-10-11 06:51:42',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            16 => 
            array (
                'id' => 265,
                'user_id' => 2,
                'action_id' => 8,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-10-06 09:58:16',
                'updated_at' => '2016-10-06 09:58:16',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            17 => 
            array (
                'id' => 264,
                'user_id' => 93,
                'action_id' => 13,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-10-06 09:56:58',
                'updated_at' => '2016-10-06 09:56:58',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            18 => 
            array (
                'id' => 263,
                'user_id' => 93,
                'action_id' => 12,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-10-06 09:56:27',
                'updated_at' => '2016-10-06 09:56:27',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            19 => 
            array (
                'id' => 262,
                'user_id' => 2,
                'action_id' => 13,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-10-06 09:53:23',
                'updated_at' => '2016-10-06 09:53:23',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            20 => 
            array (
                'id' => 261,
                'user_id' => 92,
                'action_id' => 12,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-10-04 07:24:36',
                'updated_at' => '2016-10-04 07:24:36',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            21 => 
            array (
                'id' => 260,
                'user_id' => 91,
                'action_id' => 12,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-09-28 10:52:17',
                'updated_at' => '2016-09-28 10:52:17',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            22 => 
            array (
                'id' => 259,
                'user_id' => 33,
                'action_id' => 12,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-09-27 14:08:58',
                'updated_at' => '2016-09-27 14:08:58',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            23 => 
            array (
                'id' => 258,
                'user_id' => 43,
                'action_id' => 12,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-09-27 12:43:29',
                'updated_at' => '2016-09-27 12:43:29',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            24 => 
            array (
                'id' => 257,
                'user_id' => 90,
                'action_id' => 12,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-09-23 12:43:30',
                'updated_at' => '2016-09-23 12:43:30',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            25 => 
            array (
                'id' => 256,
                'user_id' => 89,
                'action_id' => 12,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-09-23 12:43:30',
                'updated_at' => '2016-09-23 12:43:30',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            26 => 
            array (
                'id' => 255,
                'user_id' => 88,
                'action_id' => 12,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-09-23 12:43:30',
                'updated_at' => '2016-09-23 12:43:30',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            27 => 
            array (
                'id' => 254,
                'user_id' => 87,
                'action_id' => 12,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-09-23 12:43:30',
                'updated_at' => '2016-09-23 12:43:30',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            28 => 
            array (
                'id' => 253,
                'user_id' => 86,
                'action_id' => 12,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-09-23 12:43:30',
                'updated_at' => '2016-09-23 12:43:30',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            29 => 
            array (
                'id' => 252,
                'user_id' => 85,
                'action_id' => 12,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-09-23 12:43:30',
                'updated_at' => '2016-09-23 12:43:30',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            30 => 
            array (
                'id' => 251,
                'user_id' => 84,
                'action_id' => 12,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-09-23 12:43:30',
                'updated_at' => '2016-09-23 12:43:30',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            31 => 
            array (
                'id' => 250,
                'user_id' => 83,
                'action_id' => 12,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-09-23 12:43:30',
                'updated_at' => '2016-09-23 12:43:30',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            32 => 
            array (
                'id' => 249,
                'user_id' => 82,
                'action_id' => 12,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-09-23 12:43:30',
                'updated_at' => '2016-09-23 12:43:30',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            33 => 
            array (
                'id' => 248,
                'user_id' => 6,
                'action_id' => 12,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-09-23 12:43:30',
                'updated_at' => '2016-09-23 12:43:30',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            34 => 
            array (
                'id' => 247,
                'user_id' => 80,
                'action_id' => 12,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-09-23 12:43:30',
                'updated_at' => '2016-09-23 12:43:30',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            35 => 
            array (
                'id' => 246,
                'user_id' => 79,
                'action_id' => 12,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-09-23 12:43:30',
                'updated_at' => '2016-09-23 12:43:30',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            36 => 
            array (
                'id' => 245,
                'user_id' => 3,
                'action_id' => 12,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-09-23 12:43:30',
                'updated_at' => '2016-09-23 12:43:30',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            37 => 
            array (
                'id' => 244,
                'user_id' => 17,
                'action_id' => 12,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-09-23 12:43:30',
                'updated_at' => '2016-09-23 12:43:30',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            38 => 
            array (
                'id' => 243,
                'user_id' => 18,
                'action_id' => 12,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-09-23 12:43:30',
                'updated_at' => '2016-09-23 12:43:30',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            39 => 
            array (
                'id' => 242,
                'user_id' => 19,
                'action_id' => 12,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-09-23 12:43:30',
                'updated_at' => '2016-09-23 12:43:30',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            40 => 
            array (
                'id' => 241,
                'user_id' => 20,
                'action_id' => 12,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-09-23 12:43:30',
                'updated_at' => '2016-09-23 12:43:30',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            41 => 
            array (
                'id' => 240,
                'user_id' => 21,
                'action_id' => 12,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-09-23 12:43:30',
                'updated_at' => '2016-09-23 12:43:30',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            42 => 
            array (
                'id' => 239,
                'user_id' => 22,
                'action_id' => 12,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-09-23 12:43:30',
                'updated_at' => '2016-09-23 12:43:30',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            43 => 
            array (
                'id' => 238,
                'user_id' => 23,
                'action_id' => 12,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-09-23 12:43:30',
                'updated_at' => '2016-09-23 12:43:30',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            44 => 
            array (
                'id' => 237,
                'user_id' => 24,
                'action_id' => 12,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-09-23 12:43:30',
                'updated_at' => '2016-09-23 12:43:30',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            45 => 
            array (
                'id' => 236,
                'user_id' => 27,
                'action_id' => 12,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-09-23 12:43:30',
                'updated_at' => '2016-09-23 12:43:30',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            46 => 
            array (
                'id' => 235,
                'user_id' => 30,
                'action_id' => 12,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-09-23 12:43:30',
                'updated_at' => '2016-09-23 12:43:30',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            47 => 
            array (
                'id' => 234,
                'user_id' => 32,
                'action_id' => 12,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-09-23 12:43:30',
                'updated_at' => '2016-09-23 12:43:30',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            48 => 
            array (
                'id' => 233,
                'user_id' => 35,
                'action_id' => 12,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-09-23 12:43:30',
                'updated_at' => '2016-09-23 12:43:30',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            49 => 
            array (
                'id' => 232,
                'user_id' => 39,
                'action_id' => 12,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-09-23 12:43:30',
                'updated_at' => '2016-09-23 12:43:30',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            50 => 
            array (
                'id' => 231,
                'user_id' => 42,
                'action_id' => 12,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-09-23 12:43:30',
                'updated_at' => '2016-09-23 12:43:30',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            51 => 
            array (
                'id' => 230,
                'user_id' => 45,
                'action_id' => 12,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-09-23 12:43:30',
                'updated_at' => '2016-09-23 12:43:30',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            52 => 
            array (
                'id' => 229,
                'user_id' => 47,
                'action_id' => 12,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-09-23 12:43:30',
                'updated_at' => '2016-09-23 12:43:30',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            53 => 
            array (
                'id' => 228,
                'user_id' => 48,
                'action_id' => 12,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-09-23 12:43:30',
                'updated_at' => '2016-09-23 12:43:30',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            54 => 
            array (
                'id' => 227,
                'user_id' => 49,
                'action_id' => 12,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-09-23 12:43:30',
                'updated_at' => '2016-09-23 12:43:30',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            55 => 
            array (
                'id' => 226,
                'user_id' => 50,
                'action_id' => 12,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-09-23 12:43:30',
                'updated_at' => '2016-09-23 12:43:30',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            56 => 
            array (
                'id' => 225,
                'user_id' => 52,
                'action_id' => 12,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-09-23 12:43:30',
                'updated_at' => '2016-09-23 12:43:30',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            57 => 
            array (
                'id' => 224,
                'user_id' => 54,
                'action_id' => 12,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-09-23 12:43:30',
                'updated_at' => '2016-09-23 12:43:30',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            58 => 
            array (
                'id' => 223,
                'user_id' => 55,
                'action_id' => 12,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-09-23 12:43:30',
                'updated_at' => '2016-09-23 12:43:30',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            59 => 
            array (
                'id' => 222,
                'user_id' => 57,
                'action_id' => 12,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-09-23 12:43:30',
                'updated_at' => '2016-09-23 12:43:30',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            60 => 
            array (
                'id' => 221,
                'user_id' => 59,
                'action_id' => 12,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-09-23 12:43:30',
                'updated_at' => '2016-09-23 12:43:30',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            61 => 
            array (
                'id' => 220,
                'user_id' => 63,
                'action_id' => 12,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-09-23 12:43:30',
                'updated_at' => '2016-09-23 12:43:30',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            62 => 
            array (
                'id' => 219,
                'user_id' => 64,
                'action_id' => 12,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-09-23 12:43:30',
                'updated_at' => '2016-09-23 12:43:30',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            63 => 
            array (
                'id' => 218,
                'user_id' => 65,
                'action_id' => 12,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-09-23 12:43:30',
                'updated_at' => '2016-09-23 12:43:30',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            64 => 
            array (
                'id' => 217,
                'user_id' => 76,
                'action_id' => 12,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-09-23 12:43:30',
                'updated_at' => '2016-09-23 12:43:30',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            65 => 
            array (
                'id' => 216,
                'user_id' => 75,
                'action_id' => 12,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-09-23 12:43:30',
                'updated_at' => '2016-09-23 12:43:30',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            66 => 
            array (
                'id' => 215,
                'user_id' => 62,
                'action_id' => 12,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-09-23 12:43:30',
                'updated_at' => '2016-09-23 12:43:30',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            67 => 
            array (
                'id' => 214,
                'user_id' => 60,
                'action_id' => 12,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-09-23 12:43:30',
                'updated_at' => '2016-09-23 12:43:30',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            68 => 
            array (
                'id' => 213,
                'user_id' => 12,
                'action_id' => 12,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-09-23 12:43:30',
                'updated_at' => '2016-09-23 12:43:30',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            69 => 
            array (
                'id' => 212,
                'user_id' => 13,
                'action_id' => 12,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-09-23 12:43:30',
                'updated_at' => '2016-09-23 12:43:30',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            70 => 
            array (
                'id' => 211,
                'user_id' => 37,
                'action_id' => 12,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-09-23 12:43:30',
                'updated_at' => '2016-09-23 12:43:30',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            71 => 
            array (
                'id' => 210,
                'user_id' => 14,
                'action_id' => 12,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-09-23 12:43:30',
                'updated_at' => '2016-09-23 12:43:30',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            72 => 
            array (
                'id' => 209,
                'user_id' => 15,
                'action_id' => 12,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-09-23 12:43:30',
                'updated_at' => '2016-09-23 12:43:30',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            73 => 
            array (
                'id' => 208,
                'user_id' => 7,
                'action_id' => 12,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-09-23 12:43:30',
                'updated_at' => '2016-09-23 12:43:30',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            74 => 
            array (
                'id' => 207,
                'user_id' => 53,
                'action_id' => 12,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-09-23 12:43:30',
                'updated_at' => '2016-09-23 12:43:30',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            75 => 
            array (
                'id' => 206,
                'user_id' => 16,
                'action_id' => 12,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-09-23 12:43:30',
                'updated_at' => '2016-09-23 12:43:30',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            76 => 
            array (
                'id' => 205,
                'user_id' => 71,
                'action_id' => 12,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-09-23 12:43:30',
                'updated_at' => '2016-09-23 12:43:30',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            77 => 
            array (
                'id' => 204,
                'user_id' => 72,
                'action_id' => 12,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-09-23 12:43:30',
                'updated_at' => '2016-09-23 12:43:30',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            78 => 
            array (
                'id' => 203,
                'user_id' => 9,
                'action_id' => 12,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-09-23 12:43:30',
                'updated_at' => '2016-09-23 12:43:30',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            79 => 
            array (
                'id' => 202,
                'user_id' => 56,
                'action_id' => 12,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-09-23 12:43:30',
                'updated_at' => '2016-09-23 12:43:30',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            80 => 
            array (
                'id' => 201,
                'user_id' => 2,
                'action_id' => 18,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-09-23 12:42:49',
                'updated_at' => '2016-09-23 12:42:49',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
            81 => 
            array (
                'id' => 200,
                'user_id' => 2,
                'action_id' => 12,
                'mail_template_id' => NULL,
                'message' => NULL,
                'created_at' => '2016-09-23 12:21:17',
                'updated_at' => '2016-09-23 12:21:17',
                'deleted_at' => NULL,
                'uni_quest_id' => NULL,
                'uni_outkey' => NULL,
                'transaction_user_id' => NULL,
            ),
        ));
        
    	
    }
}
