<?php

use Illuminate\Database\Seeder;

class ActionsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::connection('pgsql')->table('actions')->delete();
        
        \DB::connection('pgsql')->table('actions')->insert(array (
            0 => 
            array (
                'id' => 57,
                'code' => NULL,
                'name' => 'Видеозаписка с функцией записи',
                'description' => NULL,
                'quest_id' => 14,
                'up_role_id' => NULL,
                'init' => false,
                'open' => false,
                'close_quest' => false,
                'inventary' => false,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'button' => NULL,
            ),
            1 => 
            array (
                'id' => 56,
                'code' => NULL,
                'name' => 'Сертификат на бытовую технику',
                'description' => NULL,
                'quest_id' => 16,
                'up_role_id' => NULL,
                'init' => false,
                'open' => false,
                'close_quest' => false,
                'inventary' => false,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'button' => NULL,
            ),
            2 => 
            array (
                'id' => 55,
                'code' => NULL,
                'name' => 'Годовая цель',
                'description' => 'Зачесть одну годовую цель как на 100% выполненную',
                'quest_id' => 16,
                'up_role_id' => NULL,
                'init' => false,
                'open' => false,
                'close_quest' => false,
                'inventary' => false,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'button' => NULL,
            ),
            3 => 
            array (
                'id' => 54,
                'code' => NULL,
                'name' => 'Пицца на рабочее место',
                'description' => 'Когда голоден',
                'quest_id' => 15,
                'up_role_id' => NULL,
                'init' => false,
                'open' => false,
                'close_quest' => false,
                'inventary' => false,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'button' => NULL,
            ),
            4 => 
            array (
                'id' => 53,
                'code' => NULL,
                'name' => 'Теплый шарф и перчатки',
                'description' => 'Чтобы не замерзнуть по дороге домой',
                'quest_id' => 14,
                'up_role_id' => NULL,
                'init' => false,
                'open' => false,
                'close_quest' => false,
                'inventary' => false,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'button' => NULL,
            ),
            5 => 
            array (
                'id' => 52,
                'code' => NULL,
                'name' => 'Рюкзак Samsonite',
                'description' => NULL,
                'quest_id' => 14,
                'up_role_id' => NULL,
                'init' => false,
                'open' => false,
                'close_quest' => false,
                'inventary' => false,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'button' => NULL,
            ),
            6 => 
            array (
                'id' => 51,
                'code' => NULL,
                'name' => 'Фирменная термокружка',
                'description' => 'Для долгих зимних вечеров',
                'quest_id' => 14,
                'up_role_id' => NULL,
                'init' => false,
                'open' => false,
                'close_quest' => false,
                'inventary' => false,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'button' => NULL,
            ),
            7 => 
            array (
                'id' => 50,
                'code' => NULL,
                'name' => 'Хоккейная толстовка сборной России',
                'description' => 'Для настоящих фанатов',
                'quest_id' => 14,
                'up_role_id' => NULL,
                'init' => false,
                'open' => false,
                'close_quest' => false,
                'inventary' => false,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'button' => NULL,
            ),
            8 => 
            array (
                'id' => 49,
                'code' => NULL,
                'name' => 'Всегда полезная флешка на 16 гб',
                'description' => '',
                'quest_id' => 14,
                'up_role_id' => NULL,
                'init' => false,
                'open' => false,
                'close_quest' => false,
                'inventary' => false,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'button' => NULL,
            ),
            9 => 
            array (
                'id' => 48,
                'code' => NULL,
                'name' => 'Селфи-монопод',
                'description' => 'Для отличных фото',
                'quest_id' => 14,
                'up_role_id' => NULL,
                'init' => false,
                'open' => false,
                'close_quest' => false,
                'inventary' => false,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'button' => NULL,
            ),
            10 => 
            array (
                'id' => 47,
                'code' => NULL,
                'name' => 'Powerbank',
                'description' => 'Красивое и компактное зарядное устройство на 2600 mAh',
                'quest_id' => 14,
                'up_role_id' => NULL,
                'init' => false,
                'open' => false,
                'close_quest' => false,
                'inventary' => false,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'button' => NULL,
            ),
            11 => 
            array (
                'id' => 46,
                'code' => NULL,
                'name' => 'Универсальный картридер',
                'description' => NULL,
                'quest_id' => 14,
                'up_role_id' => NULL,
                'init' => false,
                'open' => false,
                'close_quest' => false,
                'inventary' => false,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'button' => NULL,
            ),
            12 => 
            array (
                'id' => 45,
                'code' => NULL,
                'name' => 'Ежедневник',
                'description' => 'Чтобы записать самое важное',
                'quest_id' => 14,
                'up_role_id' => NULL,
                'init' => false,
                'open' => false,
                'close_quest' => false,
                'inventary' => false,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'button' => NULL,
            ),
            13 => 
            array (
                'id' => 44,
                'code' => NULL,
                'name' => 'Небольшая спортивная сумка',
                'description' => '',
                'quest_id' => 14,
                'up_role_id' => NULL,
                'init' => false,
                'open' => false,
                'close_quest' => false,
                'inventary' => false,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'button' => NULL,
            ),
            14 => 
            array (
                'id' => 43,
                'code' => NULL,
                'name' => '2 билета на культурное мероприятие',
                'description' => 'Кино, концерт, выступления и т.д.',
                'quest_id' => 14,
                'up_role_id' => NULL,
                'init' => false,
                'open' => false,
                'close_quest' => false,
                'inventary' => false,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'button' => NULL,
            ),
            15 => 
            array (
                'id' => 42,
                'code' => NULL,
                'name' => '2 билета на спорт',
                'description' => 'Хоккей, футбол и т.д. ',
                'quest_id' => 14,
                'up_role_id' => NULL,
                'init' => false,
                'open' => false,
                'close_quest' => false,
                'inventary' => false,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'button' => NULL,
            ),
            16 => 
            array (
                'id' => 41,
                'code' => NULL,
                'name' => 'Летняя сумка',
                'description' => 'Подойдет для сменной обуви или для пляжных принадлежностей',
                'quest_id' => 14,
                'up_role_id' => NULL,
                'init' => false,
                'open' => false,
                'close_quest' => false,
                'inventary' => false,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'button' => NULL,
            ),
            17 => 
            array (
                'id' => 40,
                'code' => NULL,
                'name' => 'Непромокаемый чехол для телефона',
                'description' => NULL,
                'quest_id' => 14,
                'up_role_id' => NULL,
                'init' => false,
                'open' => false,
                'close_quest' => false,
                'inventary' => false,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'button' => NULL,
            ),
            18 => 
            array (
                'id' => 39,
                'code' => NULL,
                'name' => '3 кг яблок',
                'description' => 'Для заряда витаминами и хорошим настроением',
                'quest_id' => 15,
                'up_role_id' => NULL,
                'init' => false,
                'open' => false,
                'close_quest' => false,
                'inventary' => false,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'button' => NULL,
            ),
            19 => 
            array (
                'id' => 38,
                'code' => NULL,
                'name' => '3 кг мандаринов',
                'description' => 'Для заряда хорошим настроением и витаминами',
                'quest_id' => 15,
                'up_role_id' => NULL,
                'init' => false,
                'open' => false,
                'close_quest' => false,
                'inventary' => false,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'button' => NULL,
            ),
            20 => 
            array (
                'id' => 37,
                'code' => NULL,
                'name' => 'Книга о связи',
            'description' => 'ну или что-то такое :)',
            'quest_id' => 14,
            'up_role_id' => NULL,
            'init' => false,
            'open' => false,
            'close_quest' => false,
            'inventary' => false,
            'created_at' => NULL,
            'updated_at' => NULL,
            'deleted_at' => NULL,
            'button' => NULL,
        ),
        21 => 
        array (
            'id' => 36,
            'code' => NULL,
            'name' => 'Отрывной календарь на 3 месяца Мегафон',
            'description' => NULL,
            'quest_id' => 14,
            'up_role_id' => NULL,
            'init' => false,
            'open' => false,
            'close_quest' => false,
            'inventary' => false,
            'created_at' => NULL,
            'updated_at' => NULL,
            'deleted_at' => NULL,
            'button' => NULL,
        ),
        22 => 
        array (
            'id' => 35,
            'code' => NULL,
            'name' => 'Плакат "троянский конь"',
            'description' => NULL,
            'quest_id' => 14,
            'up_role_id' => NULL,
            'init' => false,
            'open' => false,
            'close_quest' => false,
            'inventary' => false,
            'created_at' => NULL,
            'updated_at' => NULL,
            'deleted_at' => NULL,
            'button' => NULL,
        ),
        23 => 
        array (
            'id' => 34,
            'code' => NULL,
            'name' => 'Рюкзак МегаФон',
            'description' => NULL,
            'quest_id' => 14,
            'up_role_id' => NULL,
            'init' => false,
            'open' => false,
            'close_quest' => false,
            'inventary' => false,
            'created_at' => NULL,
            'updated_at' => NULL,
            'deleted_at' => NULL,
            'button' => NULL,
        ),
        24 => 
        array (
            'id' => 33,
            'code' => NULL,
            'name' => 'Фирменный зонт-трость',
            'description' => 'Вдруг пойдет дождь.

Особенность – привязать к тем проектам, которыми занимаются люди – MNP, SFA, GF, LIS и прочее. Надписи, принты и раскрас соответственно делать под линейку продуктов / проектов. Ну и сделать мини-конкурс на тему, какие принты / раскрас / надписи захотят люди.',
            'quest_id' => 14,
            'up_role_id' => NULL,
            'init' => false,
            'open' => false,
            'close_quest' => false,
            'inventary' => false,
            'created_at' => NULL,
            'updated_at' => NULL,
            'deleted_at' => NULL,
            'button' => NULL,
        ),
        25 => 
        array (
            'id' => 32,
            'code' => NULL,
            'name' => 'Кепка МегаФон',
            'description' => NULL,
            'quest_id' => 14,
            'up_role_id' => NULL,
            'init' => false,
            'open' => false,
            'close_quest' => false,
            'inventary' => false,
            'created_at' => NULL,
            'updated_at' => NULL,
            'deleted_at' => NULL,
            'button' => NULL,
        ),
        26 => 
        array (
            'id' => 31,
            'code' => NULL,
            'name' => 'Шарфик МегаФон',
            'description' => NULL,
            'quest_id' => 14,
            'up_role_id' => NULL,
            'init' => false,
            'open' => false,
            'close_quest' => false,
            'inventary' => false,
            'created_at' => NULL,
            'updated_at' => NULL,
            'deleted_at' => NULL,
            'button' => NULL,
        ),
        27 => 
        array (
            'id' => 30,
            'code' => NULL,
            'name' => 'Блокнот "МегаФон"',
            'description' => NULL,
            'quest_id' => 14,
            'up_role_id' => NULL,
            'init' => false,
            'open' => false,
            'close_quest' => false,
            'inventary' => false,
            'created_at' => NULL,
            'updated_at' => NULL,
            'deleted_at' => NULL,
            'button' => NULL,
        ),
        28 => 
        array (
            'id' => 29,
            'code' => NULL,
            'name' => 'Толстовка МегаФон',
            'description' => NULL,
            'quest_id' => 14,
            'up_role_id' => NULL,
            'init' => false,
            'open' => false,
            'close_quest' => false,
            'inventary' => false,
            'created_at' => NULL,
            'updated_at' => NULL,
            'deleted_at' => NULL,
            'button' => NULL,
        ),
        29 => 
        array (
            'id' => 28,
            'code' => NULL,
            'name' => 'кружка МегаФон',
            'description' => NULL,
            'quest_id' => 14,
            'up_role_id' => NULL,
            'init' => false,
            'open' => false,
            'close_quest' => false,
            'inventary' => false,
            'created_at' => NULL,
            'updated_at' => NULL,
            'deleted_at' => NULL,
            'button' => NULL,
        ),
        30 => 
        array (
            'id' => 27,
            'code' => NULL,
            'name' => 'Фирменный брелок для ключей',
            'description' => NULL,
            'quest_id' => 14,
            'up_role_id' => NULL,
            'init' => false,
            'open' => false,
            'close_quest' => false,
            'inventary' => false,
            'created_at' => NULL,
            'updated_at' => NULL,
            'deleted_at' => NULL,
            'button' => NULL,
        ),
        31 => 
        array (
            'id' => 26,
            'code' => NULL,
            'name' => 'Футболка МегаФон',
            'description' => NULL,
            'quest_id' => 14,
            'up_role_id' => NULL,
            'init' => false,
            'open' => false,
            'close_quest' => false,
            'inventary' => false,
            'created_at' => NULL,
            'updated_at' => NULL,
            'deleted_at' => NULL,
            'button' => NULL,
        ),
        32 => 
        array (
            'id' => 25,
            'code' => NULL,
            'name' => 'Сходить в кино',
            'description' => NULL,
            'quest_id' => 14,
            'up_role_id' => NULL,
            'init' => false,
            'open' => false,
            'close_quest' => false,
            'inventary' => false,
            'created_at' => NULL,
            'updated_at' => NULL,
            'deleted_at' => NULL,
            'button' => NULL,
        ),
        33 => 
        array (
            'id' => 24,
            'code' => NULL,
            'name' => 'Сходить в аквапарк',
            'description' => NULL,
            'quest_id' => 14,
            'up_role_id' => NULL,
            'init' => false,
            'open' => false,
            'close_quest' => false,
            'inventary' => false,
            'created_at' => NULL,
            'updated_at' => NULL,
            'deleted_at' => NULL,
            'button' => NULL,
        ),
        34 => 
        array (
            'id' => 23,
            'code' => NULL,
            'name' => 'Смотреть мультики весь день',
            'description' => NULL,
            'quest_id' => 14,
            'up_role_id' => NULL,
            'init' => false,
            'open' => false,
            'close_quest' => false,
            'inventary' => false,
            'created_at' => NULL,
            'updated_at' => NULL,
            'deleted_at' => NULL,
            'button' => NULL,
        ),
        35 => 
        array (
            'id' => 22,
            'code' => NULL,
            'name' => 'Посмотреть мультики 1ч',
            'description' => NULL,
            'quest_id' => 14,
            'up_role_id' => NULL,
            'init' => false,
            'open' => false,
            'close_quest' => false,
            'inventary' => false,
            'created_at' => NULL,
            'updated_at' => NULL,
            'deleted_at' => NULL,
            'button' => NULL,
        ),
        36 => 
        array (
            'id' => 21,
            'code' => 'compensatoryHoliday',
            'name' => 'Отгул',
            'description' => NULL,
            'quest_id' => 15,
            'up_role_id' => NULL,
            'init' => false,
            'open' => false,
            'close_quest' => false,
            'inventary' => false,
            'created_at' => NULL,
            'updated_at' => NULL,
            'deleted_at' => NULL,
            'button' => NULL,
        ),
        37 => 
        array (
            'id' => 20,
            'code' => NULL,
            'name' => 'ПолПятницы',
            'description' => 'Устал? Сделай перерыв.',
            'quest_id' => 15,
            'up_role_id' => NULL,
            'init' => false,
            'open' => false,
            'close_quest' => false,
            'inventary' => false,
            'created_at' => NULL,
            'updated_at' => NULL,
            'deleted_at' => NULL,
            'button' => NULL,
        ),
        38 => 
        array (
            'id' => 19,
            'code' => 'yearGoal',
            'name' => 'Зачесть годовую цель как выполненую',
            'description' => 'Очень дорогой, но ценный приз - 1 годовая цель будет зачтена как выполненная.',
            'quest_id' => 14,
            'up_role_id' => NULL,
            'init' => false,
            'open' => false,
            'close_quest' => false,
            'inventary' => false,
            'created_at' => NULL,
            'updated_at' => NULL,
            'deleted_at' => NULL,
            'button' => NULL,
        ),
        39 => 
        array (
            'id' => 18,
            'code' => 'VladyJiraInit',
            'name' => 'Наличие доступа в Jira детектированно!',
            'description' => 'При нахождении логина этот квест автоматом: закрывается, даёт роль jiraVlady.',
            'quest_id' => 12,
            'up_role_id' => 15,
            'init' => false,
            'open' => false,
            'close_quest' => true,
            'inventary' => false,
            'created_at' => NULL,
            'updated_at' => NULL,
            'deleted_at' => NULL,
            'button' => NULL,
        ),
        40 => 
        array (
            'id' => 17,
            'code' => 'VladyJiraClosedBugFull',
            'name' => 'Со всеми необходимыми атрибутами',
            'description' => NULL,
            'quest_id' => 13,
            'up_role_id' => NULL,
            'init' => false,
            'open' => false,
            'close_quest' => false,
            'inventary' => false,
            'created_at' => NULL,
            'updated_at' => NULL,
            'deleted_at' => NULL,
            'button' => NULL,
        ),
        41 => 
        array (
            'id' => 16,
            'code' => 'VladyJiraClosedBugLite',
            'name' => 'Бонус за закрытие бага',
            'description' => NULL,
            'quest_id' => 13,
            'up_role_id' => NULL,
            'init' => false,
            'open' => false,
            'close_quest' => false,
            'inventary' => false,
            'created_at' => NULL,
            'updated_at' => NULL,
            'deleted_at' => NULL,
            'button' => NULL,
        ),
        42 => 
        array (
            'id' => 13,
            'code' => 'OpenInvite',
            'name' => 'Проверить',
            'description' => 'Инвайт есть и он берётся из инвентаря',
            'quest_id' => 0,
            'up_role_id' => 1,
            'init' => false,
            'open' => false,
            'close_quest' => true,
            'inventary' => true,
            'created_at' => NULL,
            'updated_at' => NULL,
            'deleted_at' => NULL,
            'button' => true,
        ),
        43 => 
        array (
            'id' => 12,
            'code' => 'FindInvite',
            'name' => 'В поисках приглашения',
            'description' => 'Игрок захотел присоединиться',
            'quest_id' => 0,
            'up_role_id' => NULL,
            'init' => false,
            'open' => true,
            'close_quest' => false,
            'inventary' => false,
            'created_at' => NULL,
            'updated_at' => NULL,
            'deleted_at' => NULL,
            'button' => NULL,
        ),
        44 => 
        array (
            'id' => 11,
            'code' => 'welcome',
            'name' => 'Добро пожаловать!',
            'description' => 'Доступен для взятия 1й квест',
            'quest_id' => 0,
            'up_role_id' => NULL,
            'init' => true,
            'open' => false,
            'close_quest' => false,
            'inventary' => false,
            'created_at' => NULL,
            'updated_at' => NULL,
            'deleted_at' => NULL,
            'button' => NULL,
        ),
        45 => 
        array (
            'id' => 9,
            'code' => NULL,
            'name' => 'Использовать',
            'description' => 'маленькую красную',
            'quest_id' => 5,
            'up_role_id' => NULL,
            'init' => false,
            'open' => false,
            'close_quest' => false,
            'inventary' => false,
            'created_at' => NULL,
            'updated_at' => NULL,
            'deleted_at' => NULL,
            'button' => NULL,
        ),
        46 => 
        array (
            'id' => 8,
            'code' => NULL,
            'name' => 'invite',
            'description' => 'Можно пригласить друга в игру. Открывает квест - прокачай друга.',
            'quest_id' => 14,
            'up_role_id' => NULL,
            'init' => false,
            'open' => false,
            'close_quest' => false,
            'inventary' => false,
            'created_at' => NULL,
            'updated_at' => NULL,
            'deleted_at' => NULL,
            'button' => NULL,
        ),
        47 => 
        array (
            'id' => 7,
            'code' => NULL,
            'name' => 'Средняя красная бутылка',
            'description' => 'Увеличивает HP',
            'quest_id' => 14,
            'up_role_id' => NULL,
            'init' => false,
            'open' => false,
            'close_quest' => false,
            'inventary' => false,
            'created_at' => NULL,
            'updated_at' => NULL,
            'deleted_at' => NULL,
            'button' => NULL,
        ),
        48 => 
        array (
            'id' => 6,
            'code' => NULL,
            'name' => 'Маленькая крассная бутылка',
            'description' => 'Увеличивает HP',
            'quest_id' => 14,
            'up_role_id' => NULL,
            'init' => false,
            'open' => false,
            'close_quest' => false,
            'inventary' => false,
            'created_at' => NULL,
            'updated_at' => NULL,
            'deleted_at' => NULL,
            'button' => NULL,
        ),
        49 => 
        array (
            'id' => 4,
            'code' => NULL,
            'name' => 'Завершение квеста Заполни профиль',
            'description' => NULL,
            'quest_id' => 2,
            'up_role_id' => NULL,
            'init' => false,
            'open' => false,
            'close_quest' => false,
            'inventary' => false,
            'created_at' => NULL,
            'updated_at' => NULL,
            'deleted_at' => NULL,
            'button' => NULL,
        ),
        50 => 
        array (
            'id' => 3,
            'code' => NULL,
            'name' => 'Взятие квеста Заполни профиль',
            'description' => NULL,
            'quest_id' => 2,
            'up_role_id' => NULL,
            'init' => false,
            'open' => false,
            'close_quest' => false,
            'inventary' => false,
            'created_at' => NULL,
            'updated_at' => NULL,
            'deleted_at' => NULL,
            'button' => NULL,
        ),
        51 => 
        array (
            'id' => 2,
            'code' => NULL,
            'name' => 'Выполнение квеста игроком',
            'description' => '',
            'quest_id' => 1,
            'up_role_id' => NULL,
            'init' => false,
            'open' => false,
            'close_quest' => false,
            'inventary' => false,
            'created_at' => NULL,
            'updated_at' => NULL,
            'deleted_at' => NULL,
            'button' => NULL,
        ),
        52 => 
        array (
            'id' => 1,
            'code' => NULL,
            'name' => 'Взятие квеста игроком',
            'description' => '',
            'quest_id' => 1,
            'up_role_id' => NULL,
            'init' => false,
            'open' => false,
            'close_quest' => false,
            'inventary' => false,
            'created_at' => NULL,
            'updated_at' => NULL,
            'deleted_at' => NULL,
            'button' => NULL,
        ),
    ));
        
    	
    }
}
