<?php

use Illuminate\Database\Seeder;

class ActionsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::connection('pgsql')->table('actions')->delete();
        
        \DB::connection('pgsql')->table('actions')->insert(array (
            0 => 
            array (
                'id' => 39,
                'code' => NULL,
                'name' => 'Килограмм яблок',
                'description' => NULL,
                'quest_id' => 3,
                'up_role_id' => NULL,
                'init' => false,
                'open' => false,
                'close_quest' => false,
                'inventary' => false,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'button' => NULL,
            ),
            1 => 
            array (
                'id' => 38,
                'code' => NULL,
                'name' => 'Килограмм мандаринов',
                'description' => NULL,
                'quest_id' => 3,
                'up_role_id' => NULL,
                'init' => false,
                'open' => false,
                'close_quest' => false,
                'inventary' => false,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'button' => NULL,
            ),
            2 => 
            array (
                'id' => 37,
                'code' => NULL,
                'name' => 'Книга о связи',
            'description' => 'ну или что-то такое :)',
            'quest_id' => 3,
            'up_role_id' => NULL,
            'init' => false,
            'open' => false,
            'close_quest' => false,
            'inventary' => false,
            'created_at' => NULL,
            'updated_at' => NULL,
            'deleted_at' => NULL,
            'button' => NULL,
        ),
        3 => 
        array (
            'id' => 36,
            'code' => NULL,
            'name' => 'Отрывной календарь на 3 месяца Мегафон',
            'description' => NULL,
            'quest_id' => 3,
            'up_role_id' => NULL,
            'init' => false,
            'open' => false,
            'close_quest' => false,
            'inventary' => false,
            'created_at' => NULL,
            'updated_at' => NULL,
            'deleted_at' => NULL,
            'button' => NULL,
        ),
        4 => 
        array (
            'id' => 35,
            'code' => NULL,
            'name' => 'Плакат "троянский конь"',
            'description' => NULL,
            'quest_id' => 3,
            'up_role_id' => NULL,
            'init' => false,
            'open' => false,
            'close_quest' => false,
            'inventary' => false,
            'created_at' => NULL,
            'updated_at' => NULL,
            'deleted_at' => NULL,
            'button' => NULL,
        ),
        5 => 
        array (
            'id' => 34,
            'code' => NULL,
            'name' => 'Рюкзак МегаФон',
            'description' => NULL,
            'quest_id' => 3,
            'up_role_id' => NULL,
            'init' => false,
            'open' => false,
            'close_quest' => false,
            'inventary' => false,
            'created_at' => NULL,
            'updated_at' => NULL,
            'deleted_at' => NULL,
            'button' => NULL,
        ),
        6 => 
        array (
            'id' => 33,
            'code' => NULL,
            'name' => 'Зонтик МегаФон',
            'description' => 'Особенность – привязать к тем проектам, которыми занимаются люди – MNP, SFA, GF, LIS и прочее. Надписи, принты и раскрас соответственно делать под линейку продуктов / проектов. Ну и сделать мини-конкурс на тему, какие принты / раскрас / надписи захотят люди.',
            'quest_id' => 3,
            'up_role_id' => NULL,
            'init' => false,
            'open' => false,
            'close_quest' => false,
            'inventary' => false,
            'created_at' => NULL,
            'updated_at' => NULL,
            'deleted_at' => NULL,
            'button' => NULL,
        ),
        7 => 
        array (
            'id' => 32,
            'code' => NULL,
            'name' => 'Кепка МегаФон',
            'description' => NULL,
            'quest_id' => 3,
            'up_role_id' => NULL,
            'init' => false,
            'open' => false,
            'close_quest' => false,
            'inventary' => false,
            'created_at' => NULL,
            'updated_at' => NULL,
            'deleted_at' => NULL,
            'button' => NULL,
        ),
        8 => 
        array (
            'id' => 31,
            'code' => NULL,
            'name' => 'Шарфик МегаФон',
            'description' => NULL,
            'quest_id' => 3,
            'up_role_id' => NULL,
            'init' => false,
            'open' => false,
            'close_quest' => false,
            'inventary' => false,
            'created_at' => NULL,
            'updated_at' => NULL,
            'deleted_at' => NULL,
            'button' => NULL,
        ),
        9 => 
        array (
            'id' => 30,
            'code' => NULL,
            'name' => 'Блокнот МегаФон',
            'description' => NULL,
            'quest_id' => 3,
            'up_role_id' => NULL,
            'init' => false,
            'open' => false,
            'close_quest' => false,
            'inventary' => false,
            'created_at' => NULL,
            'updated_at' => NULL,
            'deleted_at' => NULL,
            'button' => NULL,
        ),
        10 => 
        array (
            'id' => 29,
            'code' => NULL,
            'name' => 'Толстовка МегаФон',
            'description' => NULL,
            'quest_id' => 3,
            'up_role_id' => NULL,
            'init' => false,
            'open' => false,
            'close_quest' => false,
            'inventary' => false,
            'created_at' => NULL,
            'updated_at' => NULL,
            'deleted_at' => NULL,
            'button' => NULL,
        ),
        11 => 
        array (
            'id' => 28,
            'code' => NULL,
            'name' => 'кружка МегаФон',
            'description' => NULL,
            'quest_id' => 3,
            'up_role_id' => NULL,
            'init' => false,
            'open' => false,
            'close_quest' => false,
            'inventary' => false,
            'created_at' => NULL,
            'updated_at' => NULL,
            'deleted_at' => NULL,
            'button' => NULL,
        ),
        12 => 
        array (
            'id' => 27,
            'code' => NULL,
            'name' => 'брелок МегаФон',
            'description' => NULL,
            'quest_id' => 3,
            'up_role_id' => NULL,
            'init' => false,
            'open' => false,
            'close_quest' => false,
            'inventary' => false,
            'created_at' => NULL,
            'updated_at' => NULL,
            'deleted_at' => NULL,
            'button' => NULL,
        ),
        13 => 
        array (
            'id' => 26,
            'code' => NULL,
            'name' => 'Футболка МегаФон',
            'description' => NULL,
            'quest_id' => 3,
            'up_role_id' => NULL,
            'init' => false,
            'open' => false,
            'close_quest' => false,
            'inventary' => false,
            'created_at' => NULL,
            'updated_at' => NULL,
            'deleted_at' => NULL,
            'button' => NULL,
        ),
        14 => 
        array (
            'id' => 25,
            'code' => NULL,
            'name' => 'Сходить в кино',
            'description' => NULL,
            'quest_id' => 3,
            'up_role_id' => NULL,
            'init' => false,
            'open' => false,
            'close_quest' => false,
            'inventary' => false,
            'created_at' => NULL,
            'updated_at' => NULL,
            'deleted_at' => NULL,
            'button' => NULL,
        ),
        15 => 
        array (
            'id' => 24,
            'code' => NULL,
            'name' => 'Сходить в аквапарк',
            'description' => NULL,
            'quest_id' => 3,
            'up_role_id' => NULL,
            'init' => false,
            'open' => false,
            'close_quest' => false,
            'inventary' => false,
            'created_at' => NULL,
            'updated_at' => NULL,
            'deleted_at' => NULL,
            'button' => NULL,
        ),
        16 => 
        array (
            'id' => 23,
            'code' => NULL,
            'name' => 'Смотреть мультики весь день',
            'description' => NULL,
            'quest_id' => 3,
            'up_role_id' => NULL,
            'init' => false,
            'open' => false,
            'close_quest' => false,
            'inventary' => false,
            'created_at' => NULL,
            'updated_at' => NULL,
            'deleted_at' => NULL,
            'button' => NULL,
        ),
        17 => 
        array (
            'id' => 22,
            'code' => NULL,
            'name' => 'Посмотреть мультики 1ч',
            'description' => NULL,
            'quest_id' => 3,
            'up_role_id' => NULL,
            'init' => false,
            'open' => false,
            'close_quest' => false,
            'inventary' => false,
            'created_at' => NULL,
            'updated_at' => NULL,
            'deleted_at' => NULL,
            'button' => NULL,
        ),
        18 => 
        array (
            'id' => 21,
            'code' => 'compensatoryHoliday',
            'name' => 'Отгул',
            'description' => NULL,
            'quest_id' => 3,
            'up_role_id' => NULL,
            'init' => false,
            'open' => false,
            'close_quest' => false,
            'inventary' => false,
            'created_at' => NULL,
            'updated_at' => NULL,
            'deleted_at' => NULL,
            'button' => NULL,
        ),
        19 => 
        array (
            'id' => 20,
            'code' => NULL,
            'name' => 'ПолПятницы',
            'description' => 'Устал? Сделай перерыв.',
            'quest_id' => 3,
            'up_role_id' => NULL,
            'init' => false,
            'open' => false,
            'close_quest' => false,
            'inventary' => false,
            'created_at' => NULL,
            'updated_at' => NULL,
            'deleted_at' => NULL,
            'button' => NULL,
        ),
        20 => 
        array (
            'id' => 19,
            'code' => 'yearGoal',
            'name' => 'Зачесть годовую цель как выполненую',
            'description' => 'Очень дорогой, но ценный приз - 1 годовая цель будет зачтена как выполненная.',
            'quest_id' => 3,
            'up_role_id' => NULL,
            'init' => false,
            'open' => false,
            'close_quest' => false,
            'inventary' => false,
            'created_at' => NULL,
            'updated_at' => NULL,
            'deleted_at' => NULL,
            'button' => NULL,
        ),
        21 => 
        array (
            'id' => 18,
            'code' => 'VladyJiraInit',
            'name' => 'Наличие доступа в Jira детектированно!',
            'description' => 'При нахождении логина этот квест автоматом: закрывается, даёт роль jiraVlady.',
            'quest_id' => 12,
            'up_role_id' => 15,
            'init' => false,
            'open' => false,
            'close_quest' => true,
            'inventary' => false,
            'created_at' => NULL,
            'updated_at' => NULL,
            'deleted_at' => NULL,
            'button' => NULL,
        ),
        22 => 
        array (
            'id' => 17,
            'code' => 'VladyJiraClosedBugFull',
            'name' => 'Со всеми необходимыми атрибутами',
            'description' => NULL,
            'quest_id' => 13,
            'up_role_id' => NULL,
            'init' => false,
            'open' => false,
            'close_quest' => false,
            'inventary' => false,
            'created_at' => NULL,
            'updated_at' => NULL,
            'deleted_at' => NULL,
            'button' => NULL,
        ),
        23 => 
        array (
            'id' => 16,
            'code' => 'VladyJiraClosedBugLite',
            'name' => 'Бонус за закрытие бага',
            'description' => NULL,
            'quest_id' => 13,
            'up_role_id' => NULL,
            'init' => false,
            'open' => false,
            'close_quest' => false,
            'inventary' => false,
            'created_at' => NULL,
            'updated_at' => NULL,
            'deleted_at' => NULL,
            'button' => NULL,
        ),
        24 => 
        array (
            'id' => 13,
            'code' => 'OpenInvite',
            'name' => 'Проверить',
            'description' => 'Инвайт есть и он берётся из инвентаря',
            'quest_id' => 0,
            'up_role_id' => 1,
            'init' => false,
            'open' => false,
            'close_quest' => true,
            'inventary' => true,
            'created_at' => NULL,
            'updated_at' => NULL,
            'deleted_at' => NULL,
            'button' => true,
        ),
        25 => 
        array (
            'id' => 12,
            'code' => 'FindInvite',
            'name' => 'В поисках приглашения',
            'description' => 'Игрок захотел присоединиться',
            'quest_id' => 0,
            'up_role_id' => NULL,
            'init' => false,
            'open' => true,
            'close_quest' => false,
            'inventary' => false,
            'created_at' => NULL,
            'updated_at' => NULL,
            'deleted_at' => NULL,
            'button' => NULL,
        ),
        26 => 
        array (
            'id' => 11,
            'code' => 'welcome',
            'name' => 'Добро пожаловать!',
            'description' => 'Доступен для взятия 1й квест',
            'quest_id' => 0,
            'up_role_id' => NULL,
            'init' => true,
            'open' => false,
            'close_quest' => false,
            'inventary' => false,
            'created_at' => NULL,
            'updated_at' => NULL,
            'deleted_at' => NULL,
            'button' => NULL,
        ),
        27 => 
        array (
            'id' => 9,
            'code' => NULL,
            'name' => 'Использовать',
            'description' => 'маленькую красную',
            'quest_id' => 5,
            'up_role_id' => NULL,
            'init' => false,
            'open' => false,
            'close_quest' => false,
            'inventary' => false,
            'created_at' => NULL,
            'updated_at' => NULL,
            'deleted_at' => NULL,
            'button' => NULL,
        ),
        28 => 
        array (
            'id' => 8,
            'code' => NULL,
            'name' => 'invite',
            'description' => 'Можно пригласить друга в игру. Открывает квест - прокачай друга.',
            'quest_id' => 3,
            'up_role_id' => NULL,
            'init' => false,
            'open' => false,
            'close_quest' => false,
            'inventary' => false,
            'created_at' => NULL,
            'updated_at' => NULL,
            'deleted_at' => NULL,
            'button' => NULL,
        ),
        29 => 
        array (
            'id' => 7,
            'code' => NULL,
            'name' => 'Средняя красная бутылка',
            'description' => 'Увеличивает HP',
            'quest_id' => 3,
            'up_role_id' => NULL,
            'init' => false,
            'open' => false,
            'close_quest' => false,
            'inventary' => false,
            'created_at' => NULL,
            'updated_at' => NULL,
            'deleted_at' => NULL,
            'button' => NULL,
        ),
        30 => 
        array (
            'id' => 6,
            'code' => NULL,
            'name' => 'Маленькая крассная бутылка',
            'description' => 'Увеличивает HP',
            'quest_id' => 3,
            'up_role_id' => NULL,
            'init' => false,
            'open' => false,
            'close_quest' => false,
            'inventary' => false,
            'created_at' => NULL,
            'updated_at' => NULL,
            'deleted_at' => NULL,
            'button' => NULL,
        ),
        31 => 
        array (
            'id' => 4,
            'code' => NULL,
            'name' => 'Завершение квеста Заполни профиль',
            'description' => NULL,
            'quest_id' => 2,
            'up_role_id' => NULL,
            'init' => false,
            'open' => false,
            'close_quest' => false,
            'inventary' => false,
            'created_at' => NULL,
            'updated_at' => NULL,
            'deleted_at' => NULL,
            'button' => NULL,
        ),
        32 => 
        array (
            'id' => 3,
            'code' => NULL,
            'name' => 'Взятие квеста Заполни профиль',
            'description' => NULL,
            'quest_id' => 2,
            'up_role_id' => NULL,
            'init' => false,
            'open' => false,
            'close_quest' => false,
            'inventary' => false,
            'created_at' => NULL,
            'updated_at' => NULL,
            'deleted_at' => NULL,
            'button' => NULL,
        ),
        33 => 
        array (
            'id' => 2,
            'code' => NULL,
            'name' => 'Выполнение квеста игроком',
            'description' => '',
            'quest_id' => 1,
            'up_role_id' => NULL,
            'init' => false,
            'open' => false,
            'close_quest' => false,
            'inventary' => false,
            'created_at' => NULL,
            'updated_at' => NULL,
            'deleted_at' => NULL,
            'button' => NULL,
        ),
        34 => 
        array (
            'id' => 1,
            'code' => NULL,
            'name' => 'Взятие квеста игроком',
            'description' => '',
            'quest_id' => 1,
            'up_role_id' => NULL,
            'init' => false,
            'open' => false,
            'close_quest' => false,
            'inventary' => false,
            'created_at' => NULL,
            'updated_at' => NULL,
            'deleted_at' => NULL,
            'button' => NULL,
        ),
    ));
        
    	
    }
}
