<?php

use Illuminate\Database\Seeder;

class ActionCurrenciesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::connection('pgsql')->table('action_currencies')->delete();
        
        \DB::connection('pgsql')->table('action_currencies')->insert(array (
            0 => 
            array (
                'id' => 40,
                'code' => NULL,
                'name' => 'Видеозаписка -',
                'description' => 'Цена покупки',
                'currency_id' => 4,
                'action_id' => 57,
                'value' => -500,
                'transaction_user' => true,
                'organization_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 39,
                'code' => NULL,
                'name' => 'Сертификат -',
                'description' => 'Цена покупки',
                'currency_id' => 4,
                'action_id' => 56,
                'value' => -9999,
                'transaction_user' => true,
                'organization_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 38,
                'code' => NULL,
                'name' => 'Годовая цель -',
                'description' => 'Цена покупки',
                'currency_id' => 4,
                'action_id' => 55,
                'value' => -9999,
                'transaction_user' => true,
                'organization_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 37,
                'code' => NULL,
                'name' => 'Пицца -',
                'description' => 'Цена покупки',
                'currency_id' => 4,
                'action_id' => 54,
                'value' => -600,
                'transaction_user' => true,
                'organization_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 36,
                'code' => NULL,
                'name' => 'Мандарины -',
                'description' => 'Цена покупки',
                'currency_id' => 4,
                'action_id' => 38,
                'value' => -600,
                'transaction_user' => true,
                'organization_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 35,
                'code' => NULL,
                'name' => 'Яблоки -',
                'description' => 'Цена покупки',
                'currency_id' => 4,
                'action_id' => 39,
                'value' => -600,
                'transaction_user' => true,
                'organization_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 34,
                'code' => NULL,
                'name' => 'Отгул -',
                'description' => 'Цена покупки',
                'currency_id' => 4,
                'action_id' => 21,
                'value' => -800,
                'transaction_user' => true,
                'organization_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 33,
                'code' => NULL,
                'name' => 'ПолПятницы -',
                'description' => 'Цена покупки',
                'currency_id' => 4,
                'action_id' => 20,
                'value' => -400,
                'transaction_user' => true,
                'organization_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 32,
                'code' => NULL,
                'name' => 'Шарф и перчатки -',
                'description' => 'Цена покупки',
                'currency_id' => 4,
                'action_id' => 53,
                'value' => -600,
                'transaction_user' => true,
                'organization_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 31,
                'code' => NULL,
                'name' => 'Рюкзак Samsonite -',
                'description' => 'Цена покупки',
                'currency_id' => 4,
                'action_id' => 52,
                'value' => -1500,
                'transaction_user' => true,
                'organization_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 30,
                'code' => NULL,
                'name' => 'Фирменная термокружка -',
                'description' => 'Цена покупки',
                'currency_id' => 4,
                'action_id' => 51,
                'value' => -900,
                'transaction_user' => true,
                'organization_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 29,
                'code' => NULL,
                'name' => 'Хоккейная толстовка -',
                'description' => 'Цена покупки',
                'currency_id' => 4,
                'action_id' => 50,
                'value' => -1300,
                'transaction_user' => true,
                'organization_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 28,
                'code' => NULL,
                'name' => 'Флешка -',
                'description' => 'Цена покупки',
                'currency_id' => 4,
                'action_id' => 49,
                'value' => -1000,
                'transaction_user' => true,
                'organization_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 27,
                'code' => NULL,
                'name' => 'Селфи-монопод -',
                'description' => 'Цена покупки',
                'currency_id' => 4,
                'action_id' => 48,
                'value' => -750,
                'transaction_user' => true,
                'organization_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 26,
                'code' => NULL,
                'name' => 'Powerbank -',
                'description' => 'Цена покупки',
                'currency_id' => 4,
                'action_id' => 47,
                'value' => -700,
                'transaction_user' => true,
                'organization_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 25,
                'code' => NULL,
                'name' => 'Универсальный картридер -',
                'description' => 'Цена покупки',
                'currency_id' => 4,
                'action_id' => 46,
                'value' => -500,
                'transaction_user' => true,
                'organization_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 24,
                'code' => NULL,
                'name' => 'Ежедневник -',
                'description' => 'Цена покупки',
                'currency_id' => 4,
                'action_id' => 45,
                'value' => -700,
                'transaction_user' => true,
                'organization_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 23,
                'code' => NULL,
                'name' => 'Фирменный зонт -',
                'description' => 'Цена покупки',
                'currency_id' => 4,
                'action_id' => 33,
                'value' => -1300,
                'transaction_user' => true,
                'organization_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 22,
                'code' => NULL,
                'name' => 'Спортивная сумка -',
                'description' => 'Цена покупки',
                'currency_id' => 4,
                'action_id' => 44,
                'value' => -700,
                'transaction_user' => true,
                'organization_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 21,
                'code' => NULL,
                'name' => 'Культурное мероприятие -',
                'description' => 'Цена покупки',
                'currency_id' => 4,
                'action_id' => 43,
                'value' => -500,
                'transaction_user' => true,
                'organization_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 20,
                'code' => NULL,
                'name' => 'Спорт -',
                'description' => 'Цена покупки',
                'currency_id' => 4,
                'action_id' => 42,
                'value' => -500,
                'transaction_user' => true,
                'organization_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 19,
                'code' => NULL,
                'name' => 'Летняя сумка -',
                'description' => 'Цена покупки',
                'currency_id' => 4,
                'action_id' => 41,
                'value' => -350,
                'transaction_user' => true,
                'organization_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 18,
                'code' => NULL,
                'name' => 'Чехол -',
                'description' => 'Цена покупки',
                'currency_id' => 4,
                'action_id' => 40,
                'value' => -250,
                'transaction_user' => true,
                'organization_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 17,
                'code' => NULL,
                'name' => 'Брелок -',
                'description' => 'Цена покупки',
                'currency_id' => 4,
                'action_id' => 27,
                'value' => -150,
                'transaction_user' => true,
                'organization_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 16,
                'code' => NULL,
                'name' => 'Блокнот -',
                'description' => 'Цена покупки',
                'currency_id' => 4,
                'action_id' => 30,
                'value' => -100,
                'transaction_user' => true,
                'organization_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 15,
                'code' => NULL,
                'name' => NULL,
                'description' => NULL,
                'currency_id' => 2,
                'action_id' => 16,
                'value' => 4,
                'transaction_user' => true,
                'organization_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 14,
                'code' => NULL,
                'name' => NULL,
                'description' => NULL,
                'currency_id' => 2,
                'action_id' => 16,
                'value' => 3,
                'transaction_user' => true,
                'organization_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 13,
                'code' => '',
                'name' => 'gold 4',
                'description' => NULL,
                'currency_id' => 4,
                'action_id' => 17,
                'value' => 4,
                'transaction_user' => true,
                'organization_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 12,
                'code' => NULL,
                'name' => 'gold 3',
                'description' => NULL,
                'currency_id' => 4,
                'action_id' => 16,
                'value' => 3,
                'transaction_user' => true,
                'organization_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 9,
                'code' => NULL,
                'name' => 'Инвайт',
                'description' => 'приветственный бонус',
                'currency_id' => 2,
                'action_id' => 13,
                'value' => 10,
                'transaction_user' => true,
                'organization_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 8,
                'code' => NULL,
                'name' => 'Инвайт -',
                'description' => 'Списание инвайта по нажатию кнопки.',
                'currency_id' => 1,
                'action_id' => 13,
                'value' => -1,
                'transaction_user' => true,
                'organization_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 6,
                'code' => NULL,
                'name' => 'Покупка invite',
                'description' => NULL,
                'currency_id' => 1,
                'action_id' => 8,
                'value' => 1,
                'transaction_user' => true,
                'organization_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 5,
                'code' => NULL,
                'name' => 'Цена',
                'description' => NULL,
                'currency_id' => 4,
                'action_id' => 8,
                'value' => -100,
                'transaction_user' => true,
                'organization_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 3,
                'code' => NULL,
                'name' => 'Повысить голду',
                'description' => NULL,
                'currency_id' => 4,
                'action_id' => 4,
                'value' => 10,
                'transaction_user' => true,
                'organization_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 2,
                'code' => NULL,
                'name' => 'Повысить карму',
                'description' => NULL,
                'currency_id' => 3,
                'action_id' => 4,
                'value' => 5,
                'transaction_user' => true,
                'organization_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
        ));
        
    	
    }
}
