<?php

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 4,
                'login' => NULL,
                'name' => 'В Десаточку',
                'email' => NULL,
                'password' => NULL,
                'user_type' => 2,
                'user_status_id' => 1,
                'ext_login' => NULL,
                'phone_number' => NULL,
                'tab_number' => NULL,
                'description' => NULL,
                'status' => NULL,
                'photo' => NULL,
                'mail_agg_id' => NULL,
                'mail_hour' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'login' => 'Vladimir.Khonin',
                'name' => 'Владимир Хонин',
                'email' => 'Vladimir.Khonin@Megafon.ru',
                'password' => '$2y$10$Iwe6HiQA2RD67Bi6ZAfyreLTuq45Ni5kmHVeyfZPjSAjp1m1ozh/G',
                'user_type' => 1,
                'user_status_id' => 1,
                'ext_login' => NULL,
                'phone_number' => NULL,
                'tab_number' => NULL,
                'description' => NULL,
                'status' => NULL,
                'photo' => NULL,
                'mail_agg_id' => NULL,
                'mail_hour' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 10,
                'login' => 'yuri.trigub',
                'name' => 'Юрий Тригуб',
                'email' => 'Yuri.Trigub@Megafon.ru',
                'password' => '$2y$10$Iwe6HiQA2RD67Bi6ZAfyreLTuq45Ni5kmHVeyfZPjSAjp1m1ozh/G',
                'user_type' => 1,
                'user_status_id' => 1,
                'ext_login' => 'ytrigub',
                'phone_number' => '9381113331',
                'tab_number' => NULL,
                'description' => NULL,
                'status' => NULL,
                'photo' => NULL,
                'mail_agg_id' => NULL,
                'mail_hour' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 20,
                'login' => 'Vyacheslav.Sitnikov',
                'name' => 'Вячеслав Ситников',
                'email' => 'Vyacheslav.Sitnikov@Megafon.ru',
                'password' => '$2y$10$Iwe6HiQA2RD67Bi6ZAfyreLTuq45Ni5kmHVeyfZPjSAjp1m1ozh/G',
                'user_type' => 1,
                'user_status_id' => 1,
                'ext_login' => NULL,
                'phone_number' => '9265033074',
                'tab_number' => NULL,
                'description' => NULL,
                'status' => NULL,
                'photo' => NULL,
                'mail_agg_id' => NULL,
                'mail_hour' => NULL,
                'remember_token' => 'za2qHqX09fTnUnzCeJOLCojjVFAn6FfSu1GAvYWPjsyFpaLE4JmVtXK9ozSE',
                'created_at' => NULL,
                'updated_at' => '2016-07-30 08:46:49',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 9,
                'login' => 'alexey.y.zverev',
                'name' => 'Алексей Зверев',
                'email' => 'Alexey.Y.Zverev@Megafon.ru',
                'password' => '$2y$10$Iwe6HiQA2RD67Bi6ZAfyreLTuq45Ni5kmHVeyfZPjSAjp1m1ozh/G',
                'user_type' => 1,
                'user_status_id' => 1,
                'ext_login' => NULL,
                'phone_number' => NULL,
                'tab_number' => NULL,
                'description' => NULL,
                'status' => NULL,
                'photo' => NULL,
                'mail_agg_id' => NULL,
                'mail_hour' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 8,
                'login' => 'yuri.tsay',
                'name' => 'Юрий Цай',
                'email' => 'Yuri.Tsay@Megafon.ru',
                'password' => '$2y$10$Iwe6HiQA2RD67Bi6ZAfyreLTuq45Ni5kmHVeyfZPjSAjp1m1ozh/G',
                'user_type' => 1,
                'user_status_id' => 1,
                'ext_login' => 'ytsay',
                'phone_number' => '89221234567',
                'tab_number' => NULL,
                'description' => NULL,
                'status' => NULL,
                'photo' => NULL,
                'mail_agg_id' => NULL,
                'mail_hour' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 6,
                'login' => 'sergey.kadilenko',
                'name' => 'Сергей Кадиленко',
                'email' => 'Sergey.Kadilenko@Megafon.ru',
                'password' => '$2y$10$Iwe6HiQA2RD67Bi6ZAfyreLTuq45Ni5kmHVeyfZPjSAjp1m1ozh/G',
                'user_type' => 1,
                'user_status_id' => 1,
                'ext_login' => 'skadilenko',
                'phone_number' => '89201234567',
                'tab_number' => NULL,
                'description' => NULL,
                'status' => NULL,
                'photo' => NULL,
                'mail_agg_id' => NULL,
                'mail_hour' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 5,
                'login' => 'yuriy.berezin',
                'name' => 'Юрий Березин',
                'email' => 'Yuriy.Berezin@Megafon.ru',
                'password' => '$2y$10$Iwe6HiQA2RD67Bi6ZAfyreLTuq45Ni5kmHVeyfZPjSAjp1m1ozh/G',
                'user_type' => 1,
                'user_status_id' => 1,
                'ext_login' => 'yberezin',
                'phone_number' => '89201234567',
                'tab_number' => '123456',
                'description' => NULL,
                'status' => NULL,
                'photo' => NULL,
                'mail_agg_id' => NULL,
                'mail_hour' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 3,
                'login' => 'Anna.Protko',
                'name' => 'Анна Протько',
                'email' => 'Anna.Protko@Megafon.ru',
                'password' => '$2y$10$Iwe6HiQA2RD67Bi6ZAfyreLTuq45Ni5kmHVeyfZPjSAjp1m1ozh/G',
                'user_type' => 1,
                'user_status_id' => 1,
                'ext_login' => NULL,
                'phone_number' => NULL,
                'tab_number' => NULL,
                'description' => NULL,
                'status' => NULL,
                'photo' => NULL,
                'mail_agg_id' => NULL,
                'mail_hour' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 25,
                'login' => 'alexander.fetisov',
                'name' => 'Александр Фетисов',
                'email' => 'Alexander.Fetisov@Megafon.ru',
                'password' => '$2y$10$Iwe6HiQA2RD67Bi6ZAfyreLTuq45Ni5kmHVeyfZPjSAjp1m1ozh/G',
                'user_type' => 1,
                'user_status_id' => 1,
                'ext_login' => 'afetisov',
                'phone_number' => NULL,
                'tab_number' => NULL,
                'description' => NULL,
                'status' => NULL,
                'photo' => NULL,
                'mail_agg_id' => NULL,
                'mail_hour' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 33,
                'login' => 'eduard.pavlov',
                'name' => 'Эдуард Павлов',
                'email' => 'Eduard.Pavlov@Megafon.ru',
                'password' => '$2y$10$Iwe6HiQA2RD67Bi6ZAfyreLTuq45Ni5kmHVeyfZPjSAjp1m1ozh/G',
                'user_type' => 1,
                'user_status_id' => 1,
                'ext_login' => 'epavlov',
                'phone_number' => NULL,
                'tab_number' => NULL,
                'description' => NULL,
                'status' => NULL,
                'photo' => NULL,
                'mail_agg_id' => NULL,
                'mail_hour' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 34,
                'login' => 'Fedor.Volokhin',
                'name' => 'Федор Волохин',
                'email' => 'Fedor.Volokhin@Megafon.ru',
                'password' => '$2y$10$Iwe6HiQA2RD67Bi6ZAfyreLTuq45Ni5kmHVeyfZPjSAjp1m1ozh/G',
                'user_type' => 1,
                'user_status_id' => 1,
                'ext_login' => 'FVolokhin',
                'phone_number' => NULL,
                'tab_number' => NULL,
                'description' => NULL,
                'status' => NULL,
                'photo' => NULL,
                'mail_agg_id' => NULL,
                'mail_hour' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 36,
                'login' => 'Oleg.Skorobogaty',
                'name' => 'Олег Скоробогатый',
                'email' => 'Oleg.Skorobogaty@Megafon.ru',
                'password' => '$2y$10$Iwe6HiQA2RD67Bi6ZAfyreLTuq45Ni5kmHVeyfZPjSAjp1m1ozh/G',
                'user_type' => 1,
                'user_status_id' => 1,
                'ext_login' => 'OSkorobogaty',
                'phone_number' => NULL,
                'tab_number' => NULL,
                'description' => NULL,
                'status' => NULL,
                'photo' => NULL,
                'mail_agg_id' => NULL,
                'mail_hour' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 38,
                'login' => 'egor.budrin',
                'name' => 'Егор Будрин',
                'email' => 'Egor.Budrin@Megafon.ru',
                'password' => '$2y$10$Iwe6HiQA2RD67Bi6ZAfyreLTuq45Ni5kmHVeyfZPjSAjp1m1ozh/G',
                'user_type' => 1,
                'user_status_id' => 1,
                'ext_login' => 'ebudrin',
                'phone_number' => NULL,
                'tab_number' => NULL,
                'description' => NULL,
                'status' => NULL,
                'photo' => NULL,
                'mail_agg_id' => NULL,
                'mail_hour' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 40,
                'login' => 'Denis.Sorokovik',
                'name' => 'Денис Сороковик',
                'email' => 'Denis.Sorokovik@Megafon.ru',
                'password' => '$2y$10$Iwe6HiQA2RD67Bi6ZAfyreLTuq45Ni5kmHVeyfZPjSAjp1m1ozh/G',
                'user_type' => 1,
                'user_status_id' => 1,
                'ext_login' => 'DSorokovik',
                'phone_number' => NULL,
                'tab_number' => NULL,
                'description' => NULL,
                'status' => NULL,
                'photo' => NULL,
                'mail_agg_id' => NULL,
                'mail_hour' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 43,
                'login' => 'Evgeny.Beliakov',
                'name' => 'Евгений Беляков',
                'email' => 'Evgeny.Beliakov@Megafon.ru',
                'password' => '$2y$10$Iwe6HiQA2RD67Bi6ZAfyreLTuq45Ni5kmHVeyfZPjSAjp1m1ozh/G',
                'user_type' => 1,
                'user_status_id' => 1,
                'ext_login' => 'EBeliakov',
                'phone_number' => NULL,
                'tab_number' => NULL,
                'description' => NULL,
                'status' => NULL,
                'photo' => NULL,
                'mail_agg_id' => NULL,
                'mail_hour' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 21,
                'login' => 'Dmitriy.Orlov',
                'name' => 'Дмитрий Орлов',
                'email' => 'Dmitriy.Orlov@Billing.ru',
                'password' => '$2y$10$Iwe6HiQA2RD67Bi6ZAfyreLTuq45Ni5kmHVeyfZPjSAjp1m1ozh/G',
                'user_type' => 1,
                'user_status_id' => 1,
                'ext_login' => NULL,
                'phone_number' => NULL,
                'tab_number' => NULL,
                'description' => NULL,
                'status' => NULL,
                'photo' => NULL,
                'mail_agg_id' => NULL,
                'mail_hour' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 16,
                'login' => 'anton.khlevitsky',
                'name' => 'Антон Хлевицкий',
                'email' => 'Anton.Khlevitsky@Megafon.ru',
                'password' => '$2y$10$Iwe6HiQA2RD67Bi6ZAfyreLTuq45Ni5kmHVeyfZPjSAjp1m1ozh/G',
                'user_type' => 1,
                'user_status_id' => 1,
                'ext_login' => NULL,
                'phone_number' => '9242581163',
                'tab_number' => NULL,
                'description' => NULL,
                'status' => NULL,
                'photo' => NULL,
                'mail_agg_id' => NULL,
                'mail_hour' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 17,
                'login' => 'nikolay.bagrov',
                'name' => 'Николай Багров',
                'email' => 'Nikolay.Bagrov@Megafon.ru',
                'password' => '$2y$10$Iwe6HiQA2RD67Bi6ZAfyreLTuq45Ni5kmHVeyfZPjSAjp1m1ozh/G',
                'user_type' => 1,
                'user_status_id' => 1,
                'ext_login' => NULL,
                'phone_number' => '9247368055',
                'tab_number' => NULL,
                'description' => NULL,
                'status' => NULL,
                'photo' => NULL,
                'mail_agg_id' => NULL,
                'mail_hour' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 18,
                'login' => 'edgar.rubtsov',
                'name' => 'Эдгар Рубцов',
                'email' => 'Edgar.Rubtsov@Megafon.ru',
                'password' => '$2y$10$Iwe6HiQA2RD67Bi6ZAfyreLTuq45Ni5kmHVeyfZPjSAjp1m1ozh/G',
                'user_type' => 1,
                'user_status_id' => 1,
                'ext_login' => NULL,
                'phone_number' => '9264304300',
                'tab_number' => NULL,
                'description' => NULL,
                'status' => NULL,
                'photo' => NULL,
                'mail_agg_id' => NULL,
                'mail_hour' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 19,
                'login' => 'dmitry.litokh',
                'name' => 'Дмитрий Литох',
                'email' => 'Dmitry.Litokh@Megafon.ru',
                'password' => '$2y$10$Iwe6HiQA2RD67Bi6ZAfyreLTuq45Ni5kmHVeyfZPjSAjp1m1ozh/G',
                'user_type' => 1,
                'user_status_id' => 1,
                'ext_login' => NULL,
                'phone_number' => '9241257955',
                'tab_number' => NULL,
                'description' => NULL,
                'status' => NULL,
                'photo' => NULL,
                'mail_agg_id' => NULL,
                'mail_hour' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'login' => 'Egor.Mamontov',
                'name' => 'Егор Мамонтов',
                'email' => 'Egor.Mamontov@Billing.ru',
                'password' => '$2y$10$Iwe6HiQA2RD67Bi6ZAfyreLTuq45Ni5kmHVeyfZPjSAjp1m1ozh/G',
                'user_type' => 1,
                'user_status_id' => 1,
                'ext_login' => NULL,
                'phone_number' => NULL,
                'tab_number' => NULL,
                'description' => NULL,
                'status' => NULL,
                'photo' => NULL,
                'mail_agg_id' => NULL,
                'mail_hour' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'login' => 'igor.a.romanov',
                'name' => 'Игорь Романов',
                'email' => 'Igor.A.Romanov@Megafon.ru',
                'password' => '$2y$10$Iwe6HiQA2RD67Bi6ZAfyreLTuq45Ni5kmHVeyfZPjSAjp1m1ozh/G',
                'user_type' => 1,
                'user_status_id' => 1,
                'ext_login' => NULL,
                'phone_number' => NULL,
                'tab_number' => NULL,
                'description' => NULL,
                'status' => NULL,
                'photo' => NULL,
                'mail_agg_id' => NULL,
                'mail_hour' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 30,
                'login' => 'alexander.a.grischenko',
                'name' => 'Александр Грищенко',
                'email' => 'Alexander.A.Grischenko@Megafon.ru',
                'password' => '$2y$10$Iwe6HiQA2RD67Bi6ZAfyreLTuq45Ni5kmHVeyfZPjSAjp1m1ozh/G',
                'user_type' => 1,
                'user_status_id' => 1,
                'ext_login' => NULL,
                'phone_number' => NULL,
                'tab_number' => NULL,
                'description' => NULL,
                'status' => NULL,
                'photo' => NULL,
                'mail_agg_id' => NULL,
                'mail_hour' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 24,
                'login' => 'Varvara.Pyatkova',
                'name' => 'Варвара Пяткова',
                'email' => 'Varvara.Pyatkova@Billing.ru',
                'password' => '$2y$10$Iwe6HiQA2RD67Bi6ZAfyreLTuq45Ni5kmHVeyfZPjSAjp1m1ozh/G',
                'user_type' => 1,
                'user_status_id' => 1,
                'ext_login' => NULL,
                'phone_number' => NULL,
                'tab_number' => NULL,
                'description' => NULL,
                'status' => NULL,
                'photo' => NULL,
                'mail_agg_id' => NULL,
                'mail_hour' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'login' => 'Mikhail.Vysokolian',
                'name' => 'Михаил Высоколян',
                'email' => 'Mikhail.Vysokolian@Megafon.ru',
                'password' => '$2y$10$Iwe6HiQA2RD67Bi6ZAfyreLTuq45Ni5kmHVeyfZPjSAjp1m1ozh/G',
                'user_type' => 1,
                'user_status_id' => 1,
                'ext_login' => 'MVysokolian',
                'phone_number' => NULL,
                'tab_number' => NULL,
                'description' => NULL,
                'status' => NULL,
                'photo' => NULL,
                'mail_agg_id' => NULL,
                'mail_hour' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'login' => 'Alexander.Mikhaylov',
                'name' => 'Александр Михайлов',
                'email' => 'Alexander.Mikhaylov@Billing.ru',
                'password' => '$2y$10$Iwe6HiQA2RD67Bi6ZAfyreLTuq45Ni5kmHVeyfZPjSAjp1m1ozh/G',
                'user_type' => 1,
                'user_status_id' => 1,
                'ext_login' => NULL,
                'phone_number' => NULL,
                'tab_number' => NULL,
                'description' => NULL,
                'status' => NULL,
                'photo' => NULL,
                'mail_agg_id' => NULL,
                'mail_hour' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 32,
                'login' => 'sergey.rzhevsky',
                'name' => 'Сергей Ржевский',
                'email' => 'Sergey.Rzhevsky@Megafon.ru',
                'password' => '$2y$10$Iwe6HiQA2RD67Bi6ZAfyreLTuq45Ni5kmHVeyfZPjSAjp1m1ozh/G',
                'user_type' => 1,
                'user_status_id' => 1,
                'ext_login' => NULL,
                'phone_number' => NULL,
                'tab_number' => NULL,
                'description' => NULL,
                'status' => NULL,
                'photo' => NULL,
                'mail_agg_id' => NULL,
                'mail_hour' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 28,
                'login' => 'sergey.grishaev',
                'name' => 'Сергей Гришаев',
                'email' => 'Sergey.Grishaev@Megafon.ru',
                'password' => '$2y$10$Iwe6HiQA2RD67Bi6ZAfyreLTuq45Ni5kmHVeyfZPjSAjp1m1ozh/G',
                'user_type' => 1,
                'user_status_id' => 1,
                'ext_login' => 'sgrishaev',
                'phone_number' => NULL,
                'tab_number' => NULL,
                'description' => NULL,
                'status' => NULL,
                'photo' => NULL,
                'mail_agg_id' => NULL,
                'mail_hour' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 35,
                'login' => 'alexander.karpachev',
                'name' => 'Александр Карпачев',
                'email' => 'Alexander.Karpachev@Megafon.ru',
                'password' => '$2y$10$Iwe6HiQA2RD67Bi6ZAfyreLTuq45Ni5kmHVeyfZPjSAjp1m1ozh/G',
                'user_type' => 1,
                'user_status_id' => 1,
                'ext_login' => NULL,
                'phone_number' => NULL,
                'tab_number' => NULL,
                'description' => NULL,
                'status' => NULL,
                'photo' => NULL,
                'mail_agg_id' => NULL,
                'mail_hour' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 37,
                'login' => 'egor.kovalchuk',
                'name' => 'Егор Ковальчук',
                'email' => 'Egor.Kovalchuk@Megafon.ru',
                'password' => '$2y$10$Iwe6HiQA2RD67Bi6ZAfyreLTuq45Ni5kmHVeyfZPjSAjp1m1ozh/G',
                'user_type' => 1,
                'user_status_id' => 1,
                'ext_login' => NULL,
                'phone_number' => NULL,
                'tab_number' => NULL,
                'description' => NULL,
                'status' => NULL,
                'photo' => NULL,
                'mail_agg_id' => NULL,
                'mail_hour' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 39,
                'login' => 'Alexey.Vyunnikov',
                'name' => 'Алексей Вьюнников',
                'email' => 'Alexey.Vyunnikov@Megafon.ru',
                'password' => '$2y$10$Iwe6HiQA2RD67Bi6ZAfyreLTuq45Ni5kmHVeyfZPjSAjp1m1ozh/G',
                'user_type' => 1,
                'user_status_id' => 1,
                'ext_login' => NULL,
                'phone_number' => NULL,
                'tab_number' => NULL,
                'description' => NULL,
                'status' => NULL,
                'photo' => NULL,
                'mail_agg_id' => NULL,
                'mail_hour' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 42,
                'login' => 'sergey.batin',
                'name' => 'Сергей Батин',
                'email' => 'Sergey.Batin@Megafon.ru',
                'password' => '$2y$10$Iwe6HiQA2RD67Bi6ZAfyreLTuq45Ni5kmHVeyfZPjSAjp1m1ozh/G',
                'user_type' => 1,
                'user_status_id' => 1,
                'ext_login' => NULL,
                'phone_number' => NULL,
                'tab_number' => NULL,
                'description' => NULL,
                'status' => NULL,
                'photo' => NULL,
                'mail_agg_id' => NULL,
                'mail_hour' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 45,
                'login' => 'Gennady.Martyushov',
                'name' => 'Геннадий Мартюшов',
                'email' => 'Gennady.Martyushov@Billing.ru',
                'password' => '$2y$10$Iwe6HiQA2RD67Bi6ZAfyreLTuq45Ni5kmHVeyfZPjSAjp1m1ozh/G',
                'user_type' => 1,
                'user_status_id' => 1,
                'ext_login' => NULL,
                'phone_number' => NULL,
                'tab_number' => NULL,
                'description' => NULL,
                'status' => NULL,
                'photo' => NULL,
                'mail_agg_id' => NULL,
                'mail_hour' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 49,
                'login' => 'roman.pyatyshev',
                'name' => 'Роман Пятышев',
                'email' => 'Roman.Pyatyshev@Megafon.ru',
                'password' => '$2y$10$Iwe6HiQA2RD67Bi6ZAfyreLTuq45Ni5kmHVeyfZPjSAjp1m1ozh/G',
                'user_type' => 1,
                'user_status_id' => 1,
                'ext_login' => NULL,
                'phone_number' => NULL,
                'tab_number' => NULL,
                'description' => NULL,
                'status' => NULL,
                'photo' => NULL,
                'mail_agg_id' => NULL,
                'mail_hour' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 47,
                'login' => 'Sergey.Semka',
                'name' => 'Сергей Семка',
                'email' => 'Sergey.Semka@Billing.ru',
                'password' => '$2y$10$Iwe6HiQA2RD67Bi6ZAfyreLTuq45Ni5kmHVeyfZPjSAjp1m1ozh/G',
                'user_type' => 1,
                'user_status_id' => 1,
                'ext_login' => NULL,
                'phone_number' => NULL,
                'tab_number' => NULL,
                'description' => NULL,
                'status' => NULL,
                'photo' => NULL,
                'mail_agg_id' => NULL,
                'mail_hour' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 48,
                'login' => 'Egor.Vershinin',
                'name' => 'Егор Вершинин',
                'email' => 'Egor.Vershinin@Billing.ru',
                'password' => '$2y$10$Iwe6HiQA2RD67Bi6ZAfyreLTuq45Ni5kmHVeyfZPjSAjp1m1ozh/G',
                'user_type' => 1,
                'user_status_id' => 1,
                'ext_login' => NULL,
                'phone_number' => NULL,
                'tab_number' => NULL,
                'description' => NULL,
                'status' => NULL,
                'photo' => NULL,
                'mail_agg_id' => NULL,
                'mail_hour' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 53,
                'login' => 'mikhail.pavlov',
                'name' => 'Михаил Павлов',
                'email' => 'Mikhail.Pavlov@Megafon.ru',
                'password' => '$2y$10$Iwe6HiQA2RD67Bi6ZAfyreLTuq45Ni5kmHVeyfZPjSAjp1m1ozh/G',
                'user_type' => 1,
                'user_status_id' => 1,
                'ext_login' => NULL,
                'phone_number' => NULL,
                'tab_number' => NULL,
                'description' => NULL,
                'status' => NULL,
                'photo' => NULL,
                'mail_agg_id' => NULL,
                'mail_hour' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 50,
                'login' => 'denis.lykov',
                'name' => 'Денис Лыков',
                'email' => 'Denis.Lykov@Megafon.ru',
                'password' => '$2y$10$Iwe6HiQA2RD67Bi6ZAfyreLTuq45Ni5kmHVeyfZPjSAjp1m1ozh/G',
                'user_type' => 1,
                'user_status_id' => 1,
                'ext_login' => NULL,
                'phone_number' => NULL,
                'tab_number' => NULL,
                'description' => NULL,
                'status' => NULL,
                'photo' => NULL,
                'mail_agg_id' => NULL,
                'mail_hour' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 52,
                'login' => 'Valentin.Kovalchuk',
                'name' => 'Валентин Ковальчук',
                'email' => 'Valentin.Kovalchuk@Megafon.ru',
                'password' => '$2y$10$Iwe6HiQA2RD67Bi6ZAfyreLTuq45Ni5kmHVeyfZPjSAjp1m1ozh/G',
                'user_type' => 1,
                'user_status_id' => 1,
                'ext_login' => NULL,
                'phone_number' => NULL,
                'tab_number' => NULL,
                'description' => NULL,
                'status' => NULL,
                'photo' => NULL,
                'mail_agg_id' => NULL,
                'mail_hour' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 56,
                'login' => 'sergey.gomzyakov',
                'name' => 'Сергей Гомзяков',
                'email' => 'Sergey.Gomzyakov@Megafon.ru',
                'password' => '$2y$10$Iwe6HiQA2RD67Bi6ZAfyreLTuq45Ni5kmHVeyfZPjSAjp1m1ozh/G',
                'user_type' => 1,
                'user_status_id' => 1,
                'ext_login' => NULL,
                'phone_number' => NULL,
                'tab_number' => NULL,
                'description' => NULL,
                'status' => NULL,
                'photo' => NULL,
                'mail_agg_id' => NULL,
                'mail_hour' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 58,
                'login' => '',
                'name' => '-=GoodWin=-',
                'email' => NULL,
                'password' => NULL,
                'user_type' => 2,
                'user_status_id' => 1,
                'ext_login' => NULL,
                'phone_number' => NULL,
                'tab_number' => NULL,
                'description' => NULL,
                'status' => NULL,
                'photo' => NULL,
                'mail_agg_id' => NULL,
                'mail_hour' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 54,
                'login' => 'anna.y.aleshina',
                'name' => 'Анна Алешина',
                'email' => 'Anna.Y.Aleshina@Megafon.ru',
                'password' => '$2y$10$Iwe6HiQA2RD67Bi6ZAfyreLTuq45Ni5kmHVeyfZPjSAjp1m1ozh/G',
                'user_type' => 1,
                'user_status_id' => 1,
                'ext_login' => NULL,
                'phone_number' => NULL,
                'tab_number' => NULL,
                'description' => NULL,
                'status' => NULL,
                'photo' => NULL,
                'mail_agg_id' => NULL,
                'mail_hour' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 55,
                'login' => 'alexander.surkov',
                'name' => 'Александр Сурков',
                'email' => 'Alexander.Surkov@Megafon.ru',
                'password' => '$2y$10$Iwe6HiQA2RD67Bi6ZAfyreLTuq45Ni5kmHVeyfZPjSAjp1m1ozh/G',
                'user_type' => 1,
                'user_status_id' => 1,
                'ext_login' => NULL,
                'phone_number' => NULL,
                'tab_number' => NULL,
                'description' => NULL,
                'status' => NULL,
                'photo' => NULL,
                'mail_agg_id' => NULL,
                'mail_hour' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 57,
                'login' => 'yana.baranova',
                'name' => 'Яна Баранова',
                'email' => 'Yana.Baranova@Megafon.ru',
                'password' => '$2y$10$Iwe6HiQA2RD67Bi6ZAfyreLTuq45Ni5kmHVeyfZPjSAjp1m1ozh/G',
                'user_type' => 1,
                'user_status_id' => 1,
                'ext_login' => NULL,
                'phone_number' => NULL,
                'tab_number' => NULL,
                'description' => NULL,
                'status' => NULL,
                'photo' => NULL,
                'mail_agg_id' => NULL,
                'mail_hour' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'id' => 59,
                'login' => 'dmitry.v.tarasov',
                'name' => 'Дмитрий Тарасов',
                'email' => 'Dmitry.V.Tarasov@Megafon.ru',
                'password' => '$2y$10$Iwe6HiQA2RD67Bi6ZAfyreLTuq45Ni5kmHVeyfZPjSAjp1m1ozh/G',
                'user_type' => 1,
                'user_status_id' => 1,
                'ext_login' => NULL,
                'phone_number' => NULL,
                'tab_number' => NULL,
                'description' => NULL,
                'status' => NULL,
                'photo' => NULL,
                'mail_agg_id' => NULL,
                'mail_hour' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            46 => 
            array (
                'id' => 60,
                'login' => 'ruslan.kazimukhometo',
                'name' => 'Руслан Казимухометов',
                'email' => 'Ruslan.Kazimukhometo@Megafon.ru',
                'password' => '$2y$10$Iwe6HiQA2RD67Bi6ZAfyreLTuq45Ni5kmHVeyfZPjSAjp1m1ozh/G',
                'user_type' => 1,
                'user_status_id' => 1,
                'ext_login' => NULL,
                'phone_number' => NULL,
                'tab_number' => NULL,
                'description' => NULL,
                'status' => NULL,
                'photo' => NULL,
                'mail_agg_id' => NULL,
                'mail_hour' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            47 => 
            array (
                'id' => 61,
                'login' => 'artem.trikashny',
                'name' => 'Артем Трикашный',
                'email' => 'Artem.Trikashny@Megafon.ru',
                'password' => '$2y$10$Iwe6HiQA2RD67Bi6ZAfyreLTuq45Ni5kmHVeyfZPjSAjp1m1ozh/G',
                'user_type' => 1,
                'user_status_id' => 1,
                'ext_login' => NULL,
                'phone_number' => NULL,
                'tab_number' => NULL,
                'description' => NULL,
                'status' => NULL,
                'photo' => NULL,
                'mail_agg_id' => NULL,
                'mail_hour' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            48 => 
            array (
                'id' => 62,
                'login' => 'svetlana.a.kuznetsova',
                'name' => 'Светлана Кузнецова',
                'email' => 'Svetlana.A.Kuznetsova@Megafon.ru',
                'password' => '$2y$10$Iwe6HiQA2RD67Bi6ZAfyreLTuq45Ni5kmHVeyfZPjSAjp1m1ozh/G',
                'user_type' => 1,
                'user_status_id' => 1,
                'ext_login' => NULL,
                'phone_number' => NULL,
                'tab_number' => NULL,
                'description' => NULL,
                'status' => NULL,
                'photo' => NULL,
                'mail_agg_id' => NULL,
                'mail_hour' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            49 => 
            array (
                'id' => 63,
                'login' => 'evgeny.fomenko',
                'name' => 'Евгений Фоменко',
                'email' => 'Evgeny.Fomenko@Megafon.ru',
                'password' => '$2y$10$Iwe6HiQA2RD67Bi6ZAfyreLTuq45Ni5kmHVeyfZPjSAjp1m1ozh/G',
                'user_type' => 1,
                'user_status_id' => 1,
                'ext_login' => NULL,
                'phone_number' => NULL,
                'tab_number' => NULL,
                'description' => NULL,
                'status' => NULL,
                'photo' => NULL,
                'mail_agg_id' => NULL,
                'mail_hour' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            50 => 
            array (
                'id' => 64,
                'login' => 'Irina.Imaykina',
                'name' => 'Ирина Имайкина',
                'email' => 'Irina.Imaykina@Megafon.ru',
                'password' => '$2y$10$Iwe6HiQA2RD67Bi6ZAfyreLTuq45Ni5kmHVeyfZPjSAjp1m1ozh/G',
                'user_type' => 1,
                'user_status_id' => 1,
                'ext_login' => NULL,
                'phone_number' => NULL,
                'tab_number' => NULL,
                'description' => NULL,
                'status' => NULL,
                'photo' => NULL,
                'mail_agg_id' => NULL,
                'mail_hour' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            51 => 
            array (
                'id' => 65,
                'login' => 'grigory.osipenkov',
                'name' => 'Григорий Осипенков',
                'email' => 'Grigory.Osipenkov@Megafon.ru',
                'password' => '$2y$10$Iwe6HiQA2RD67Bi6ZAfyreLTuq45Ni5kmHVeyfZPjSAjp1m1ozh/G',
                'user_type' => 1,
                'user_status_id' => 1,
                'ext_login' => NULL,
                'phone_number' => NULL,
                'tab_number' => NULL,
                'description' => NULL,
                'status' => NULL,
                'photo' => NULL,
                'mail_agg_id' => NULL,
                'mail_hour' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            52 => 
            array (
                'id' => 66,
                'login' => NULL,
                'name' => 'M-Team',
                'email' => NULL,
                'password' => NULL,
                'user_type' => 2,
                'user_status_id' => 1,
                'ext_login' => NULL,
                'phone_number' => NULL,
                'tab_number' => NULL,
                'description' => NULL,
                'status' => NULL,
                'photo' => NULL,
                'mail_agg_id' => NULL,
                'mail_hour' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            53 => 
            array (
                'id' => 67,
                'login' => NULL,
                'name' => 'Я Команда Миру-Мир ПС',
                'email' => NULL,
                'password' => NULL,
                'user_type' => 2,
                'user_status_id' => 1,
                'ext_login' => NULL,
                'phone_number' => NULL,
                'tab_number' => NULL,
                'description' => NULL,
                'status' => NULL,
                'photo' => NULL,
                'mail_agg_id' => NULL,
                'mail_hour' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            54 => 
            array (
                'id' => 68,
                'login' => NULL,
                'name' => 'VeryFine',
                'email' => NULL,
                'password' => NULL,
                'user_type' => 2,
                'user_status_id' => 1,
                'ext_login' => NULL,
                'phone_number' => NULL,
                'tab_number' => NULL,
                'description' => NULL,
                'status' => NULL,
                'photo' => NULL,
                'mail_agg_id' => NULL,
                'mail_hour' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            55 => 
            array (
                'id' => 7,
                'login' => 'ruslan.revel',
                'name' => 'Руслан Ревель',
                'email' => 'Ruslan.Revel@Megafon.ru',
                'password' => '$2y$10$Iwe6HiQA2RD67Bi6ZAfyreLTuq45Ni5kmHVeyfZPjSAjp1m1ozh/G',
                'user_type' => 1,
                'user_status_id' => 1,
                'ext_login' => NULL,
                'phone_number' => '9247274966',
                'tab_number' => NULL,
                'description' => NULL,
                'status' => NULL,
                'photo' => NULL,
                'mail_agg_id' => NULL,
                'mail_hour' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            56 => 
            array (
                'id' => 69,
                'login' => NULL,
                'name' => 'Vyuacheslav',
                'email' => 'Vyacjeslav.Sitnikov@Megafon.ru',
                'password' => '$2y$10$mkVLQ69UWlfPeu933N2ceu.wJLbTtDTJzTpRHfO.NCe4SAv5YpYL6',
                'user_type' => 1,
                'user_status_id' => 1,
                'ext_login' => NULL,
                'phone_number' => NULL,
                'tab_number' => NULL,
                'description' => NULL,
                'status' => NULL,
                'photo' => NULL,
                'mail_agg_id' => NULL,
                'mail_hour' => NULL,
                'remember_token' => NULL,
                'created_at' => '2016-07-30 08:43:50',
                'updated_at' => '2016-07-30 08:43:50',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}
