#SELECT 'php artisan iseed '|| substr(tablename,5) x FROM pg_catalog.pg_tables where schemaname='wog' and tablename!='wog_migrations'
php artisan iseed UserStatus
php artisan iseed TeamUser
php artisan iseed UserProfile
php artisan iseed RoleUser
php artisan iseed User
php artisan iseed CurrencyTypes
php artisan iseed Quest
php artisan iseed Role
php artisan iseed Currency
php artisan iseed UserQuestStatus
php artisan iseed Balance
php artisan iseed UserQuest
php artisan iseed ActionCurrency
php artisan iseed MailTemplate
php artisan iseed Action
php artisan iseed ActionTrancaction
php artisan iseed jobs
php artisan iseed CurrencyTrancaction
php artisan iseed Skill
php artisan iseed pages
php artisan iseed UserSkill
