php artisan iseed organizations --force
php artisan iseed jobs --force
php artisan iseed user_quest_statuses --force
php artisan iseed currency_types --force
php artisan iseed roles --force
php artisan iseed mail_aggs --force
php artisan iseed pages --force
php artisan iseed user_statuses --force
php artisan iseed password_resets --force
php artisan iseed users --force
php artisan iseed robots --force
php artisan iseed team_users --force
php artisan iseed robots --force
php artisan iseed quests --force
php artisan iseed role_user --force
php artisan iseed currencies --force
php artisan iseed balances --force
php artisan iseed skill_levels --force
php artisan iseed skills --force
php artisan iseed actions --force
php artisan iseed quest_depends --force
php artisan iseed user_quests --force
php artisan iseed action_currencies --force
php artisan iseed mail_templates --force
php artisan iseed action_transactions --force
php artisan iseed currency_transactions --force
php artisan iseed user_skills --force