php artisan iseed UserStatus
php artisan iseed users
php artisan iseed pages
php artisan iseed CurrencyTypes
php artisan iseed password_resets
php artisan iseed Role
php artisan iseed UserQuestStatus
php artisan iseed jobs
php artisan iseed UserProfile
php artisan iseed TeamUser
php artisan iseed Quest
php artisan iseed RoleUser
php artisan iseed Currency
php artisan iseed Skill
php artisan iseed Balance
php artisan iseed Action
php artisan iseed UserQuest
php artisan iseed ActionCurrency
php artisan iseed MailTemplate
php artisan iseed ActionTransaction
php artisan iseed CurrencyTransaction
php artisan iseed UserSkill
