php artisan iseed user_statuses
php artisan iseed users
php artisan iseed pages
php artisan iseed currency_types
php artisan iseed password_resets
php artisan iseed roles
php artisan iseed user_quest_statuses
php artisan iseed jobs
php artisan iseed user_profiles
php artisan iseed team_users
php artisan iseed quest
php artisan iseed role_user
php artisan iseed currencies
php artisan iseed skills
php artisan iseed balances
php artisan iseed actions
php artisan iseed user_quests
php artisan iseed action_currences
php artisan iseed mail_template
php artisan iseed action_trancactions
php artisan iseed currency_trancactions
php artisan iseed user_skills